version: "3.9"
services:
  alurageek:
    build:
      dockerfile: dockerfile
      context: ../alura-geek/
    image: alurageek:1.0
    container_name: alurageek
    restart: always
    working_dir: /home/node/app/projeto
    networks:
      - alurageek
    ports:
      - "3030:3030"
      - "8080:8080"
    stdin_open: true
    tty: true
    volumes:
      - ../alura-geek/:/home/node/app/projeto
      - ../alura-geek/package-lock.json:/home/node/app/package-lock.json
      - ../alura-geek/package.json:/home/node/app/package.json
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=100

    depends_on:
      - "node"
      - "mysql"

  node:
    build:
      dockerfile: dockerfile
      context: ../API-AluraGeek/
    image: api-alurageek:1.0
    container_name: api-alurageek
    restart: unless-stopped
    working_dir: /home/node/app/projeto
    networks:
      - alurageek
    ports:
      - "3000:3000"
      - "8000:8000"
    stdin_open: true
    tty: true
    volumes:
      - ../API-AluraGeek/:/home/node/app/projeto
      - ../API-AluraGeek/package-lock.json:/home/node/app/package-lock.json
      - ../API-AluraGeek/package.json:/home/node/app/package.json
    depends_on:
      - "mysql"

  mysql:
    image: mysql:8.0.28-oracle
    container_name: mysql-alurageek
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: alura_geek
      MYSQL_USER: root
    ports:
      - "3306:3306"
    restart: unless-stopped
    volumes:
      - mysql:/var/lib/mysql
      - mysql_config:/etc/mysql
    networks:
      - alurageek

networks:
  alurageek:
    driver: bridge

volumes:
  mysql:
  mysql_config:
