version: "3.9"
services:
  alurageek:
    build:
      dockerfile: dockerfile
      context: ../alura-geek/
    image: alurageek:1.0
    container_name: alurageek
    # restart:always o banco inicia só
    restart: unless-stopped
    working_dir: /home/node/app/projeto
    networks:
      - frontend
    ports:
      - "3030:3030"
      - "8080:8080"
    stdin_open: true
    tty: true
    volumes:
      - ../alura-geek/:/home/node/app/projeto
      - ../alura-geek/package-lock.json:/home/node/app/package-lock.json
      - ../alura-geek/package.json:/home/node/app/package.json
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=100

    depends_on:
      - "node"
      - "mongodb"

  node:
    build:
      dockerfile: dockerfile
      context: ../API-AluraGeek/
    image: api-alurageek:1.0
    container_name: api-alurageek
    restart: unless-stopped
    working_dir: /home/node/api/src
    networks:
      - frontend
      - backend
    ports:
      - "3000:3000"
      - "8000:8000"
    stdin_open: true
    tty: true
    volumes:
      - ../API-AluraGeek/src:/home/node/api/src
      - ../API-AluraGeek/package-lock.json:/home/node/api/package-lock.json
      - ../API-AluraGeek/package.json:/home/node/api/package.json
    depends_on:
      - "mongodb"

  mongodb:
    image: mongo:4.4.6
    container_name: mongo-alurageek
    ports:
      - "27017:27017"
    volumes:
      - ../volume:/data/db
    networks: 
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge