version: "3.9"
services:
  alurageek:
    build:
      dockerfile: dockerfile
      context: ../alura-geek/
    image: alurageek:1.0
    container_name: alurageek
    restart: always
    working_dir: /home/node/app/projeto
    networks:
      - frontend
    ports:
      - "3030:3030"
      - "8080:8080"
    stdin_open: true
    tty: true
    volumes:
      - ../alura-geek/:/home/node/app/projeto
      - ../alura-geek/package-lock.json:/home/node/app/package-lock.json
      - ../alura-geek/package.json:/home/node/app/package.json
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=100

    depends_on:
      - "node"
      - "mysql"

  node:
    build:
      dockerfile: dockerfile
      context: ../API-AluraGeek/
    image: api-alurageek:1.0
    container_name: api-alurageek
    restart: unless-stopped
    working_dir: /home/node/app/api
    networks:
      - frontend
      - backend
    ports:
      - "3000:3000"
      - "8000:8000"
    stdin_open: true
    tty: true
    volumes:
      - ../API-AluraGeek/api:/home/node/app/api
      - ../API-AluraGeek/package-lock.json:/home/node/app/package-lock.json
      - ../API-AluraGeek/package.json:/home/node/app/package.json
      - ../API-AluraGeek/.sequelizerc:/home/node/app/.sequelizerc
    depends_on:
      - "mysql"

  mysql:
    image: mysql:8.0.28-oracle
    container_name: mysql-alurageek
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: alura_geek
      MYSQL_USER: Node
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - ../mysql/log:/var/log/mysql
      - ../mysql/data:/var/lib/mysql
      - ../mysql/conf:/etc/MySQL/conf.d.
    networks:
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge